services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hassan
      POSTGRES_DB: sveltekit_auth
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  embed-api:
    build: ./embed-api
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - MODEL_NAME=all-MiniLM-L6-v2

volumes:
  pgdata:
